version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testdb
      MONGO_INITDB_ROOT_PASSWORD: testdb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
